import { TimelineItemType } from '@/types/timeline';
import 'dotenv/config';
import { prisma } from '../lib/prisma';
import { ProjectItemType } from '../types/project';

const timelines: Omit<TimelineItemType, 'id'>[] = [
  {
    type: 'education',
    year: '2018',
    date: '2018/03 - 2024/02',
    place: '인천대학교',
    title: '인천대학교 컴퓨터공학부',
    descriptions: ['3.71/4.5 평점으로 졸업'],
    image: '/img/timeline/inu.svg',
  },
  {
    type: 'education',
    year: '2024',
    date: '2024/08 - 2025/02',
    place: '하나은행',
    title: '디지털 하나로',
    descriptions: ['풀스택 개발자 과정 수료', 'Next.js 및 Spring Boot 학습'],
    image: '/img/timeline/hana.png',
  },
  {
    type: 'certifications',
    year: '2024',
    date: '2024/06/21',
    place: '한국데이터산업진흥원(Kdata)',
    title: 'SQLD',
    descriptions: ['SQLD 자격증을 취득했습니다'],
    image: '/img/timeline/kdata.jpeg',
  },
  {
    type: 'experience',
    year: '2026',
    date: '~현재',
    place: 'x',
    title: '구직중',
    descriptions: ['웹 프론트엔드 개발자로 구직중입니다.'],
    image: '/img/Sion.jpeg',
  },
];

const projects: Omit<ProjectItemType, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    slug: 'one-hada',
    title: '원,하다',
    overview: '초개인화 금융 플랫폼 웹앱 서비스',
    description:
      '고령화 사회에서 디지털 취약계층은 점점 소외되고 있습니다. 은행점 감소, 유명무실한 기능의 전화상담, 복잡한 절차 등 다양한 이유로 인해 금융 서비스를 이용하기 어려움을 겪고 있습니다. 이러한 문제를 해결하기 위해 원,하다는 초개인화 금융 플랫폼 웹앱 서비스를 제공합니다.',
    category: 'Mobile',
    thumbnail: '/img/projects/one-hada/thumbnail.png',
    icon: '/img/projects/one-hada/icon.png',
    contributions: [
      '글꼴 적용',
      '내 활동 보기',
      '활동내역 페이지',
      '바로가기 페이지',
      '상담내역 페이지',
      '홈 화면',
      '즐겨찾기 무한 캐러셀',
      '전화 연결 기능',
      '추천 상품 제안 무한 캐러셀',
      'json-server 기반 테스트 환경 구축',
      '쿼리 파라미터 기반 데이터 전달 구조를 Redis 기반 구조로 개선',
      'GitHub Actions 기반 CI/CD 파이프라인 구축',
      '상담자와의 화면 공유를 위한 소켓 기반 스크린샷 전송',
      'AWS EC2 서버 구축',
      'Nginx 기반 리버스 프록시 구성',
    ],
    insights: [
      'GitHub, Trello, Notion, Figma 기반 협업',
      'GitHub Actions를 활용한 CI/CD',
      'Next.js 기반 프론트엔드 개발',
      'AWS EC2 기반 서버 구성 경험',
      'Nginx 리버스 프록시 구성',
      'Parallel Router를 활용한 페이지 구현',
      'json-server를 활용한 임시 테스트 환경 구축',
      '버튼 클릭 이벤트 전파 문제 수정',
      '서버 스왑 메모리 설정',
      'Redis를 활용한 상태 동기화',
      '경로 저장 로직을 JSON 기반으로 단순화',
    ],
    techStack: [
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'Spring',
      'JPA',
      'MySQL',
      'Redis',
      'MongoDB',
      'Neo4J',
      'AWS',
      'GitHub Actions',
    ],
    teamSize: 7,
    role: '프론트엔드 개발자',
    startDate: new Date('2024-10-18'),
    endDate: new Date('2024-12-26'),
    github: 'https://github.com/Hanaro-Trolly/ONE-HADA-FE',
    link: null,
    featured: true,
    order: 1,
  },
  {
    slug: 'pay-all',
    title: 'PayAll',
    overview: '소비습관 관리 모바일 앱 서비스',
    description:
      '온라인 쇼핑몰마다 최저가가 달라 소비자는 여러 사이트를 번거롭게 이용 기존 마이데이터 서비스는 자산 관리에 집중, 효과적인 소비 관리기능은 부족한 상황입니다. 플랫폼 통합결제, 영수증 추적, 자산관리로 소비습관을 형성하도록 도와줍니다.',
    category: 'Mobile',
    thumbnail: '/img/projects/pay-all/thumbnail.png',
    icon: '/img/projects/pay-all/icon.png',
    contributions: [
      'Naver Clova API 기반 영수증 OCR 기능',
      'Storybook 기반 컴포넌트 문서화',
      '회원가입 / 로그인 페이지',
      '계좌 목록 페이지',
      '지출 내역 페이지',
      '거래 상세 내역 페이지',
      '장바구니 페이지',
      '홈 화면',
      '광고 제공 캐러셀',
      '이전 구매 목록 컴포넌트',
      '검색 페이지',
      '로컬 스토리지를 활용한 최근 검색어 기능',
      '검색 로딩 중 스켈레톤 UI',
      'AWS EC2 서버 구축',
      'Nginx 기반 리버스 프록시 구성',
    ],
    insights: [
      'GitHub, Notion, Figma 기반 협업',
      'GitHub Actions를 활용한 CI/CD',
      'Next.js 기반 프론트엔드 개발',
      'AWS EC2 기반 서버 구성 경험',
      'Nginx 리버스 프록시 구성',
      'Framer Motion을 활용한 애니메이션 구현',
      'Storybook을 활용한 컴포넌트 명세화',
      'Clova API 기반 이미지 인식 기능 구현',
      'Next.js 서버 액션 활용',
      'Jotai 기반 상태 관리',
      'React Query 기반 데이터 패칭 및 캐싱',
      'FE/BE 서버 요청 혼선 문제를 프록시 우선순위 변경으로 해결',
      '로그인 요청에 스로틀링 적용',
      '실제 마이데이터 연동이 불가능해 Mock 서버를 별도 제작하고 API 형식에 맞춘 데이터 제공',
    ],
    techStack: [
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'React Query',
      'Jotai',
      'Spring',
      'JPA',
      'MySQL',
      'Redis',
      'AWS',
      'GitHub Actions',
    ],
    teamSize: 7,
    role: '프론트엔드 개발자',
    startDate: new Date('2024-01-08'),
    endDate: new Date('2024-02-05'),
    github: 'https://github.com/UckgiDuckgi',
    link: null,
    featured: true,
    order: 2,
  },
  {
    slug: 'kkumiroom',
    title: '꾸미룸',
    overview: '고교학점제 지원 모바일 어플리케이션',
    description:
      '고교학점제의 도입으로 달라진 수업 선택 방법이 복잡해졌습니다. 또한 필요한 정보가 흩어져 있어 원하는 정보에 접근하기 어려운 상황입니다. 꾸미룸은 고교생들이 진로를 기반으로 원하는 수업을 들을 수 있도록 도와줍니다.',
    category: 'Mobile',
    thumbnail: '/img/projects/kkumiroom/thumbnail.png',
    icon: '/img/projects/kkumiroom/icon.png',
    contributions: [
      '현재 시간에 따른 수업 활성화 기능',
      '로그인 및 회원가입',
      '시간표 컴포넌트 제작',
      '과목 정보 / 과목 목록 구현',
      '과목 검색 및 필터링 기능',
      '미들웨어에서 액세스 토큰 기반 접근 제어',
      '희망 학과 관리 및 관련 정보 제공 기능',
    ],
    insights: [
      'GitHub, Notion, Figma 기반 협업',
      'GitHub Actions를 활용한 CI/CD',
      'Next.js 기반 프론트엔드 개발',
      'AWS EC2 기반 서버 구성 경험',
      'Nginx 리버스 프록시 구성',
      'SWR 기반 데이터 패칭',
      '학교 정보 데이터 패칭 지연 문제를 Node 서버 자체 캐싱으로 개선',
      '과목 검색 시 무한 렌더링 문제를 isReady 플래그 추가로 해결',
      '테이블 rounded 적용 문제를 셀 컴포넌트화 및 래핑 구조 변경으로 해결',
    ],
    techStack: [
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'SWR',
      'Jotai',
      'Spring',
      'JPA',
      'MySQL',
      'Redis',
      'AWS',
      'GitHub Actions',
    ],
    teamSize: 3,
    role: '프론트엔드 개발자',
    startDate: new Date('2024-04-10'),
    endDate: new Date('2024-05-28'),
    github: 'https://github.com/KKumiRoom',
    link: null,
    featured: true,
    order: 3,
  },
  {
    slug: 'personal-blog',
    title: '개인 블로그',
    overview: '개인 기술 블로그',
    description:
      'MDX 기반의 개인 기술 블로그입니다. 백준 문제 풀이 시 자동 포스팅 기능을 지원합니다.',
    category: 'Web',
    thumbnail: '/img/projects/personal-blog/thumbnail.png',
    icon: '/img/projects/personal-blog/icon.png',
    contributions: [
      '백준 문제 풀이 시 블로그 자동 포스트',
      '클립보드 복사 기능',
      'MDX 기반 게시글 렌더링',
      '프로필 모달',
      '다크모드 토글',
      '로컬 스토리지를 활용한 사이드바 상태 관리',
      '카테고리별 게시글 제공',
      '최신 포스트 모아보기',
    ],
    insights: [
      '다크모드 적용',
      '프로필 모달 구현',
      'MDX 파일을 파싱해 React 컴포넌트로 렌더링',
      'GitHub Actions를 활용한 커밋 자동화',
      'GitHub Pages 배포',
      '다크모드 깜빡임 현상(FOUC) 대응',
      '브라우저 라우팅 사용 시 404 에러를 해시 라우팅으로 해결',
      'PS 문제 해결 시 자동 포스트 기능을 Chrome 확장 프로그램 + GitHub Actions 기반으로 구현',
    ],
    techStack: ['React', 'MDX', 'GitHub Pages', 'GitHub Actions'],
    teamSize: 1,
    role: '1인 개발',
    startDate: new Date('2025-05-02'),
    endDate: new Date('2025-05-12'),
    github: 'https://github.com/Sionparadox/Sionparadox.github.io',
    link: 'https://Sionparadox.github.io',
    featured: false,
    order: 4,
  },
  {
    slug: 'portfolio',
    title: '포트폴리오',
    overview: '개인 포트폴리오 웹사이트',
    description: '개인 프로젝트와 경험을 소개하는 포트폴리오 웹사이트입니다.',
    category: 'Web',
    thumbnail: '/img/projects/portfolio/thumbnail.png',
    icon: '/img/projects/portfolio/icon.png',
    contributions: [
      '모바일 / 데스크탑 반응형 UI',
      '방문 시기에 따른 인사 메시지 변화 기능',
      '메시지 폭발 애니메이션',
      '은하수 / 하늘 배경 생성 및 Web Worker 기반 최적화',
      '글래스모피즘 컴포넌트',
      '하루 1회 인트로 애니메이션',
      '메시지 전송 기능',
      '프로젝트 정보 검색 및 필터링',
      '내 정보 및 타임라인 제공',
    ],
    insights: [
      '모바일 퍼스트 반응형 UI',
      '다크모드 토글 기능',
      'Vercel 기반 서버리스 배포',
      'NeonDB와 Connection Pooling',
      'Prisma ORM',
      'Zod 유효성 검사',
      'SSR 최적화',
      '은하수 배경 사용 시 끊김 현상을 Web Worker로 완화',
      '폼 제출 시 요청 횟수 과다 우려로 스로틀링 적용',
      'Android / iOS Chrome 간 스크롤 반응 차이 확인',
    ],
    techStack: [
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'Prisma',
      'NeonDB',
      'Vercel',
    ],
    teamSize: 1,
    role: '1인 개발',
    startDate: new Date('2025-12-01'),
    endDate: new Date('2026-02-13'),
    github: 'https://github.com/Sionparadox/Portfolio',
    link: 'https://sion.is-a.dev',
    featured: true,
    order: 5,
  },
];

async function main() {
  console.log('seed.ts 실행');
  await prisma.timeline.deleteMany({});
  await prisma.project.deleteMany({});
  console.log('기존 데이터 삭제 완료');

  await prisma.timeline.createMany({ data: timelines });
  console.log('timeline 데이터 생성 완료');

  await prisma.project.createMany({ data: projects });
  console.log('project 데이터 생성 완료');
}

main()
  .catch((e) => {
    console.error('seed.ts 실행 중 오류 발생:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
